
spring:
  datasource:
    url: jdbc:mysql://192.168.100.229:3306/cpecmcr?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 1qaz@WSX
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      data-source-properties:
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true
  redis:
    host: 192.168.100.229
    port: 6379
    password: cplh1234
mybatis:
    mapper-locations: classpath:mappers/*.xml
    type-aliases-package: com.yu.domain
    #configuration:
    #  cache-enabled: true
logging:
  level:
    org.mybatis: debug
    com.yu.repository: debug